[dependencies]
serde = {features = ["derive"], version = "*"}
serde_json = "*"

[package]
description = "Command that rotates the default PipeWire audio sink"
edition = "2024"
license = "MIT"
name = "sink-rotate"
repository = "https://github.com/mightyiam/sink-rotate"
version = "2.3.0"
