[package]
name = "sink-rotate"
description = "Command that sets \"next\" PipeWire audio sink as default"
version = "1.0.3"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
