[dependencies]
serde = {features = ["derive"], version = "1.0.188"}
serde_json = "1.0.107"

[package]
description = "Command that rotates the default PipeWire audio sink"
edition = "2021"
license = "MIT"
name = "sink-rotate"
repository = "https://github.com/mightyiam/sink-rotate"
version = "2.2.0"
